### ISSUE TITLE
swagger docs are pointing to a bad environment

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-read-api#155] opened 2018-09-03 14:26 UTC
https://playground-api.windingtree.com/docs/ points to demo-api.windingtree.com

**Comment by hynek-urban** [comment] 2018-09-05 08:28
@JirkaChadima Isn't this a duplicate of #147 that has already been fixed? Or is this something else?

**Comment by JirkaChadima** [comment] 2018-09-05 08:33
This is directly in the rendered swagger docs, I think the endpoint is defined in docs/swagger.yaml and it's hardcoded to demo.

**Comment by hynek-urban** [comment] 2018-09-05 08:58
Fixed in `develop`; it will be deployed with the next release.

**Closed by hynek-urban** 2018-09-05 08:58 UTC
